#!/usr/bin/env python3
"""Trivy JSON ciktilarini okur, olcumleri Python ile hesaplar,
yorumu LLM'e yazdirir. API anahtari yoksa sadece olcumleri yazar."""
import json, os, sys, urllib.request, urllib.error
from collections import Counter
from pathlib import Path

SEV_ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "UNKNOWN": 4}
MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5-5")
LANG = os.environ.get("SUMMARY_LANG", "English")
RESULTS = Path("results")
OUT = Path("docs/trivy-summary.md")


def load(path):
    data = json.loads(Path(path).read_text())
    vulns = []
    for res in data.get("Results") or []:
        for v in res.get("Vulnerabilities") or []:
            vulns.append({
                "id": v.get("VulnerabilityID"),
                "pkg": v.get("PkgName"),
                "installed": v.get("InstalledVersion"),
                "fixed": v.get("FixedVersion") or "none",
                "severity": v.get("Severity"),
                "target": res.get("Target"),
                "title": (v.get("Title") or "")[:120],
            })
    return vulns


def stats(vulns):
    by_sev = Counter(v["severity"] for v in vulns)
    by_pkg = Counter(v["pkg"] for v in vulns)
    top = sorted(vulns, key=lambda v: (SEV_ORDER.get(v["severity"], 9), v["pkg"] or ""))[:10]
    return {
        "total": len(vulns),
        "by_severity": dict(by_sev),
        "top_packages": by_pkg.most_common(5),
        "top_findings": top,
    }


def ask_llm(payload):
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        return None
    prompt = (
        f"Below are Trivy scan statistics (HIGH/CRITICAL only) for the same Go service "
        f"packaged on two base images: alpine and wolfi. Write a short comparison in {LANG}.\n"
        "Rules: use ONLY the data given; never invent CVEs, packages or versions; "
        "keep CVE IDs exactly as given; say when a fix is not available; max 250 words.\n"
        "Structure: 1) Overall result, 2) Three most important findings, "
        "3) What the difference means in practice.\n\n"
        + json.dumps(payload, indent=2)
    )
    body = json.dumps({
        "model": MODEL,
        "max_tokens": 1000,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "content-type": "application/json",
            "x-api-key": key,
            "anthropic-version": "2023-06-01",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            resp = json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"API error {e.code}: {e.read().decode()[:300]}")
    return "".join(b.get("text", "") for b in resp["content"])


def main():
    payload = {}
    for name in ("alpine", "wolfi"):
        p = RESULTS / f"{name}.json"
        if not p.exists():
            sys.exit(f"missing {p}")
        payload[name] = stats(load(p))

    ver = RESULTS / "trivy-version-alpine.txt"
    trivy_ver = ver.read_text().strip() if ver.exists() else "unknown"

    a, w = payload["alpine"], payload["wolfi"]
    rows = []
    for sev in ("CRITICAL", "HIGH"):
        rows.append(f"| {sev} | {a['by_severity'].get(sev, 0)} | {w['by_severity'].get(sev, 0)} |")
    rows.append(f"| **Total** | {a['total']} | {w['total']} |")

    md = [
        "# Trivy scan summary",
        "",
        f"Scanner: `{trivy_ver}`",
        "",
        "## Measurements (computed by script)",
        "",
        "| Severity | Alpine | Wolfi |",
        "|---|---|---|",
        *rows,
        "",
    ]

    commentary = ask_llm(payload)
    if commentary:
        md += [
            "## Commentary (AI-generated)",
            "",
            commentary.strip(),
            "",
            f"> Generated by `{MODEL}` from the numbers above. Verify against the raw Trivy JSON.",
            "",
        ]
    else:
        md += ["_No ANTHROPIC_API_KEY set, AI commentary skipped._", ""]

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(md))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
